version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!__START_OF_PREBUILD__!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      - ls -al ~/.m2
      - aws s3 cp s3://codebuild-p1-orm-output-bucket/p1-orm/target/eorm-1.0.jar ~/.m2/repository/eteam/eorm/1.0.0-SNAPSHOT/eorm-1.0.0-SNAPSHOT.jar
      - aws s3 cp s3://codebuild-p1-orm-output-bucket/p1-orm/target/eorm-1.0.jar /root/ec2-user/eorm-1.0.jar
      #- mvn install:install-file -Dfile=~/eorm-1.0.0-SNAPSHOT.jar -DgroupId=eteam -DartifactId=eorm -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
      - mvn install:install-file -Dfile=/root/ec2-user/eorm-1.0.jar -DgroupId=eteam -DartifactId=eorm -Dversion=1.0 -Dpackaging=jar
      - ls -al ~/.m2/repository/eteam/eorm/1.0/
      - echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!END OF PREBUILD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/p1-webapp-0.1.war